name: Node CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.18.1'
      - name: Install Dependencies
        run: npm ci
      - name: Test
        run: make test
      - name: Lint
        run: make lint


      - name: Set up Docker Buildx
        if: ${{ github.event_name == 'push' }}
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        if: ${{ github.event_name == 'push' }}
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        if: ${{ github.event_name == 'push' }}
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          cache-from: hexletcomponents/js-fastify-blog:latest
          cache-to: type=inline
          tags: hexletcomponents/js-fastify-blog:latest
